### ISSUE TITLE
Runner asking for git password.

### ISSUE THREAD

**Issue by JonasMH** [gitlabhq/gitlab-ci-runner#17]
Hi, as the title says, every time the runner starts building, it asks for a git@\<ip\>'s password. I can just go "ssh git@\<ip\>" without it asking for a password. So it does not seem like a ssh key problem. Any solutions?

Also, when i just "ssh git@\<ip\>" it responds with:

PTY allocation request failed on channel 0
Welcome to GitLab, Anonymous!
Connection to \<ip\> closed.

**Comment by Razer6** [comment]
It's been at least 2 weeks (and a new release) since we heard from you. I'm closing this issue but if you still experience this problem, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
